---
spring:
  application:
    name: springboot-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_learning?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 0924

---
mybatis:
  type-aliases-package: com.tianshi.songzeyang.bean
  mapper-locations: classpath:com/tianshi/songzeyang/mapper/*.xml
